Enhance header filtering in getHeadersApplicableToAllResources function to exclude falsy values
nuxt-modules/security pull request #588
Opened 2024-12-17 20:57 UTC by ivanvakulov

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

2024-12-19 08:21 UTC, vejja requested changes

2024-12-19 08:21 UTC, vejja commented on src/utils/headers.ts
> +    .filter(([_, value]) => Boolean(value))
```suggestion
    .filter(([, value]) => Boolean(value))
```

Addresses CodeQL warning

2024-12-19 19:49 UTC, ivanvakulov commented
@vejja Thank you for the review. I've added new tests for publicAssets to ensure there are no empty headers and that headers are correctly set according to the routeRules.

2024-12-19 22:21 UTC, vejja approved these changes

2024-12-20 11:15 UTC, vejja commented
@Baroshem LGTM

2024-12-23 05:57 UTC, Baroshem approved these changes
Amazing work @ivanvakulov 

Thanks @vejja for checking it!

2024-12-30 16:00 UTC, merged